services:
  - type: web
    name: pdf-parser
    env: python
    python_version: 3.11.9
    buildCommand: >
      curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.8.4 python3 - &&
      poetry config virtualenvs.create false &&
      poetry install --no-interaction --no-ansi --no-dev
    startCommand: "poetry run gunicorn --bind 0.0.0.0:$PORT app:app"
