services:
  - type: web
    name: pdf-parser
    env: python
    python_version: 3.11.9
    buildCommand: >
      export POETRY_HOME="/opt/render/.poetry" &&
      export POETRY_CACHE_DIR="/opt/render/.cache/poetry" &&
      export PATH="/opt/render/.poetry/bin:$PATH" &&
      curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.8.4 python3 - &&
      poetry config virtualenvs.create false &&
      poetry config experimental.new-installer true &&
      poetry install --no-interaction --no-ansi --no-dev --with-credentials
    startCommand: "poetry run gunicorn --bind 0.0.0.0:$PORT app:app"
    disk:
      name: poetry-cache
      mountPath: /opt/render
      sizeGB: 1
